### ISSUE TITLE
Chant showing up only on caster in effect-menu module

### ISSUE THREAD

**Issue by v1ld** [Bubb13/EEex#43]
When testing the effect-menu module, a Chant cast on the whole party only shows up in the Shift-mouseover listing only on the caster and not the other members of the party.

Thanks for your work on EEex and on Spell Menu Extended!

**Comment by Bubb13** [comment]
Hi v1ld,

The effect-menu does the best it can automatically. Chant is hidden because it immediately splits off into subspells, and these subspells don't have any icons assigned. This doesn't affect vanilla gameplay, however, this detail means the effect-menu will interpret these subspells as internal and hide them. If you're familiar with using Near Infinity you could add icons to the subspells and the effect-menu will start picking them up.

Unfortunately there are instances of enemy-specific spells and little technicalities like this that make the effect-menu miss spells. Only way around it is to curate a list of known spells, and that's simply infeasible when considering the many game versions / mods.

**Comment by v1ld** [comment]
Makes sense. I noticed Bless didn't have the same problem.  

I find this feature really useful when playing SCS as is, so thanks much for adding it.

[https://imgur.com/2AdSXK3]()

**Comment by Bubb13** [comment]
It varies by game. Looks like BG:EE has icons assigned, but BG2:EE and IWD:EE don't.

**Comment by 4Luke4** [comment]
> It varies by game. Looks like BG:EE has icons assigned, but BG2:EE and IWD:EE don't.

Oh, you're right, didn't notice it...
